version: '2.2'

services:
    bemodule:
      container_name: dolcezampa_webservice
      image: mlabfactory/php8-apache:v1.4.2-xdebug
      volumes:
        - ./:/var/www/workdir
      networks:
        - dolcezampa
      restart: unless-stopped
      ports:
        - "8787:80"

networks:
  dolcezampa:
    external: true
    name: dolcezampa_default
