server {
    listen 80;
    server_name dolcezampa.com;
    server_name www.dolcezampa.com;

    # Per Let's Encrypt / Certbot
    location ^~ /.well-known {
        root /var/www/certbot;
        allow all;
        default_type "text/plain";
    }

    client_max_body_size 64M;

    # Rileva HTTPS da CloudFront
    set $forwarded_proto $http_cloudfront_forwarded_proto;
    if ($forwarded_proto = '') {
        set $forwarded_proto $scheme;
    }
	
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;

    location / {
        proxy_pass http://dolcezampa_prestashop:80;
	add_header Content-Security-Policy "frame-ancestors 'self' https://www.google.com https://www.gstatic.com;";
	# Forza il passaggio dell'header di autorizzazione al backend
    	proxy_set_header Authorization $http_authorization;
    	proxy_pass_header Authorization;
        # Forward degli header standard
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto https;
        proxy_request_buffering off;
#        proxy_set_header X-Forwarded-Proto $forwarded_proto;
	proxy_set_header X-Forwarded-Ssl on;	
	proxy_set_header X-Url-Scheme https; 
        # Buffer ottimizzati
        proxy_buffering off;
        proxy_buffer_size 16k;
        proxy_busy_buffers_size 24k;
        proxy_buffers 64 4k;
    }
}
