server {
    listen 80;
    server_name demo.dolcezampa.com;

    # Per Let's Encrypt / Certbot
    location ^~ /.well-known {
        root /var/www/certbot;
        allow all;
        default_type "text/plain";
    }

    client_max_body_size 64M;

    # Timeout aumentati per API lunghe
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;

    location / {
        proxy_pass http://dolcezampa_storefront:3000;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_buffer_size 16k;
        proxy_busy_buffers_size 24k;
        proxy_buffers 64 4k;
    }

    location /api {
        # Rimuovendo /api da qui, Nginx passa l'intera stringa /api/...
        proxy_pass http://dolcezampa_webservice; 

        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Ottimizzazioni per streaming/API lunghe
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_buffer_size 16k;
        proxy_busy_buffers_size 24k;
        proxy_buffers 64 4k;
    }
}